(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "https://melpa.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "elpy" "http://jorgenschaefer.github.io/packages/")

(depends-on "cask")
(depends-on "pallet")